# Generated by Django 4.0.5 on 2022-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_job', models.TextField(unique=True)),
                ('urls_job', models.TextField(unique=True)),
                ('date_job', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
