# Generated by Django 4.0.5 on 2022-07-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listblog',
            fields=[
                ('title_blog', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('name_content', models.TextField(primary_key=True, serialize=False)),
                ('urls_content', models.URLField()),
                ('title_content', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='learnm.listblog')),
            ],
        ),
    ]
